USE SysOpTechTest;

CREATE PROCEDURE `InsertUser`(
IN `SP_USERNAME ` VARCHAR(50), 
IN `SP_FK_ROLE` INT UNSIGNED, 
IN `SP_EMAIL` VARCHAR(50), 
IN `SP_PASSWORD` VARCHAR(50), 
IN `SP_PHONE` VARCHAR(10), 
IN `SP_BIRTHDAY` DATE) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
INSERT INTO T_USER(USERNAME, FK_ROLE, EMAIL, PASSWORD, PHONE, BIRTHDAY) 
VALUES (SP_USERNAME, SP_FK_ROLE, SP_EMAIL, SP_PASSWORD, SP_PHONE, SP_BIRTHDAY);